server {
    listen 4280;
    client_max_body_size 10m;
    location / {
        proxy_pass http://reference:80;
        proxy_set_header Host $http_host;
        proxy_cookie_path / /;
    }
}
server {
    listen 4281;
    client_max_body_size 10m;
    location / {
        proxy_pass http://corrections:80;
        proxy_set_header Host $http_host;
    }
}
